apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: su-pdfgen
  namespace: default
  labels:
    team: supstonad
spec:
  port: 8081
  image: { { image } }
  replicas:
    min: 1
    max: 1
  liveness:
    path: /is_alive
  readiness:
    path: /is_alive
  prometheus:
    enabled: true
    path: /prometheus
