name: Bygg og deploy ved push til master

on:
  push:
    branches:
      - master

permissions: { }

jobs:
  build:
    name: Build and push Docker container
    outputs:
      image: ${{ steps.docker-build-push.outputs.image }}
    runs-on: ubuntu-latest
    permissions:
      packages: 'write'
      contents: 'read'
      id-token: 'write'  # needed for push-image
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('gradle.properties', 'settings.gradle.properties', '**/build.gradle.kts', 'gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - uses: actions/setup-java@v4
        with:
          java-version: '19'
          distribution: 'temurin'
      - name: test and build
        run: ./gradlew test build
      - name: Build and push docker image to GAR
        uses: nais/docker-build-push@v0
        id: docker-build-push
        with:
          team: supstonad
          tag: ${{ github.sha }}

  deploy_to_dev:
    name: Deploy to dev
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write # needed for push-image
    steps:
      - uses: actions/checkout@v4
      - uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: nais.yml
          VAR: image=${{ needs.build.outputs.image }}

  deploy_to_prod:
    needs: deploy_to_dev
    name: Deploy to prod
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write # needed for push-image
    steps:
      - uses: actions/checkout@v4
      - uses: nais/deploy/actions/deploy@v2
        env:
          VAR: image=europe-north1-docker.pkg.dev/nais-management-233d/supstonad/su-pdfgen:${{ github.sha }}
          CLUSTER: prod-gcp
          RESOURCE: nais.yml

